services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Europe/London}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-0 0 0 * * *}
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_ROLLING_RESTART: ${WATCHTOWER_ROLLING_RESTART:-true}
      WATCHTOWER_NOTIFICATIONS: ${WATCHTOWER_NOTIFICATIONS:-email}
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${WATCHTOWER_NOTIFICATIONS_HOSTNAME:-}
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
